### PR TITLE
Customer Account Creation

### PR DESCRIPTION
**Pull request by wetefok**
Functionality for customers to create accounts on customer-facing website (`/store`)

Ticket: [ATS-56](https://cs375-pos-group-project.atlassian.net/jira/core/projects/ATS/board?selectedIssue=ATS-56)

- Created input fields for customer information:
   - First Name
   - Last Name
   - Phone Number
   - Email
- Created API endpoint for creating customer account `api/auth/store/account/create`
- Added validation for customer info fields, including handling duplicate emails

Testing:

- npm run start:dev
- go to `http://localhost:3000/store/account-management/`
- Ensure that site exists
- Create valid account
- Ensure that "Success" appears at top of page with 200 status code in Network tab
- Go into psql database
- Ensure that account has been added to the `customer` table with all relevant information
- Try to make another account with the same email used previously
- Ensure that "Email Already Exists" appears as failure message at top of page with 500 status code in Network tab
- Ensure that second account has not been added to psql database

### CODE REVIEW

**Review by mhxynh — APPROVED** [review]
Looks goodie to me

**Comment by nhokzminh698** [comment]
I think that the font color for home button should be whiter or the button color have some bright color!

**Comment by wetefok** [comment]
> I think that the font color for home button should be whiter or the button color have some bright color!

I think that I should be whiter. I now identify as white.

**Comment by nhokzminh698** [comment]
> > I think that the font color for home button should be whiter or the button color have some bright color!
> 
> I think that I should be whiter. I now identify as white.

??!

**Review by nhokzminh698 — APPROVED** [review]
Yuhness

**Pull request merged**
