### PR TITLE
deployment

### PR DESCRIPTION
**Pull request by gitnamehere**
Added some code to deploy the repo to fly
https://atspos.fly.dev/
Some changes:
* sample-env.json -> sample.env
* env.json -> .env
* scripts has been changed to have `:dev` appended at the end for development use, since env-cmd is required now
 * `npm run start:dev`
 * `npm run setup:dev`
 * `npm run setup-demo:dev` 
 * the other scripts are for my use only (since I control the deployed app)
 
Testing:
* Copy sample.env into .env and add in the corresponding data from env.json
* `npm i`
* `npm run setup-demo:dev`
* `npm run start:dev`
* yeah just make sure everything works lol

### CODE REVIEW

**Review by nhokzminh698 — APPROVED** [review]
Everything work with testing!

**Review by mhxynh — COMMENTED** [review]
Having trouble logging into the POS after adjusting .env to my info, not sure why. DB setup, main landing page, and eCommerce page are fine. Nothing is in quotations, ran `npm i` and `npm run setup-demo:dev`. Will attempt to revisit, but just to put on the radar.

**Comment by gitnamehere** [comment]
> Having trouble logging into the POS after adjusting .env to my info, not sure why. DB setup, main landing page, and eCommerce page are fine. Nothing is in quotations, ran `npm i` and `npm run setup-demo:dev`. Will attempt to revisit, but just to put on the radar.

try running setup-demo:dev again and see that the "Boss account created!" is logged when you start the server
(also dont forget to save the .env file after making changes)

**Review by mhxynh — APPROVED** [review]
Scratch convo above, I just clowned myself while testing. It worky!!

**Pull request merged**
