### PR TITLE
Routing

### PR DESCRIPTION
**Pull request by gitnamehere**
This PR moves the api request handlers into an api route file, and introduces a new function to query the database

query takes in the query string, value, res (for returning stuff), and setStatus (which denotes if you want to use res.setStatus or return stuff from the db) and handles the db query

Testing:
* `npm run start`
* check that the api works normally

### CODE REVIEW

**Comment by nhokzminh698** [comment]
Tried to do order and go to payment but it says subtotal is undefined.

**Comment by gitnamehere** [comment]
> Tried to do order and go to payment but it says subtotal is undefined.

may I see a screenshot of this

**Comment by nhokzminh698** [comment]
Screenshot 2024-08-15 123525
Screenshot 2024-08-15 123557

It might be because of my psql set up but this is what i see

**Comment by gitnamehere** [comment]
> Screenshot 2024-08-15 123525 Screenshot 2024-08-15 123557
> 
> It might be because of my psql set up but this is what i see

Yeah try running `npm run setup-demo` and see if it works

**Comment by nhokzminh698** [comment]
I did `npm run setup-demo` but not work for some reason in the payment screen still give undefined

**Comment by gitnamehere** [comment]
> I did `npm run setup-demo` but not work for some reason in the payment screen still give undefined

try making an order and going to http://localhost:3000/pos/payment/?id=1

**Comment by nhokzminh698** [comment]
> > I did `npm run setup-demo` but not work for some reason in the payment screen still give undefined
> 
> try making an order and going to http://localhost:3000/pos/payment/?id=1

still the same but it might be just on my side.

**Comment by gitnamehere** [comment]
@nhokzminh698 should be fixed now

**Comment by nhokzminh698** [comment]
Yuhhh I can see the numbers now!

**Review by nhokzminh698 — APPROVED** [review]
Looks goodness!!

**Review by mhxynh — APPROVED** [review]
All pages reach into API endpoints successfully for me 👍

**Pull request merged**
