### PR TITLE
Create Payment Screen: Part 2

### PR DESCRIPTION
**Pull request by mhxynh**
**Ticket:** [ATS-5: Create Payment Screen: Part 2](https://cs375-pos-group-project.atlassian.net/browse/ATS-5?atlOrigin=eyJpIjoiYjRjODk0NDVhNTEyNGMyZDg4ZDM2ZDEyM2ZjNmVmMzAiLCJwIjoiaiJ9)

- Displayed taxes and discount on front-end
- Order calculations update according to applied discount
- Added discounts table and created dummy data for discounts
- Created API endpoint to pull discount value according to discount code

Testing:
- `npm run setup-demo`
- `npm start`
- Go to `http://localhost:3000/pos/payment/?id=1` (assuming there is an existing order)
- Check if math calculations are correct
- Tax is set to 0.08
- Discount codes are "jotchua" (99% discount) and "michael" (50%)

### CODE REVIEW

**Comment by nhokzminh698** [comment]
image
My subtotal and tax has the same number (I shouldn't have picked the most expensive thing ever but).

**Review by nhokzminh698 — APPROVED** [review]
Looks good to me!!

**Comment by wetefok** [comment]
Is this missing a space? 
image
Also I'm assuming it's intended that we can't stack up discount codes?

**Comment by mhxynh** [comment]
> Is this missing a space? image Also I'm assuming it's intended that we can't stack up discount codes?

I haven't got to Tips unfortunately, but it'll update when a user specifies how much they want to tip. I'll fix the placeholder spacing in the next PR for this ticket. And yes, we shouldn't be able to stack up discount codes (I'm trying to save myself from suffering anymore)

**Review by wetefok — APPROVED** [review]
Massive Monique 💪, you absolutely dominated that payment screen project 💰! The way you implemented those discount codes 🏷️ and seamlessly integrated the tax calculations 🧮 is nothing short of genius 💡. The flow is smooth 🏄‍♀️, user experience is flawless 🎯, and everything just works like magic ✨. You've taken the whole payment process to the next level 🚀, making it easier and more intuitive for our users 🙌. Your dedication to perfection 🛠️ and your eye for detail 👀 are what set you apart 🔥. This is some top-tier work 👑, and it's clear that your contributions are making a massive impact on the success of our product 💼. Keep up the amazing work, Monique, you're a true powerhouse 🏆! Goku would be proud 🐉.

**Pull request merged**
