### PR TITLE
POS Ordering Screen part 1

### PR DESCRIPTION
**Pull request by gitnamehere**
This PR adds in the basic functionality to create and place orders in the POS with given items
Things still missing:
* Removing items from the order ticket and updating quantity
* bunch of other stuff in the screen
* 
Orders are currently stored as JSON as a map of `item_id` : `quantity`, and should be changed later (maybe to an array of order_items)

Testing:
* `npm run setup-demo`
* `npm start`
* go to `http://localhost:3000/pos/ordering`
* click on the categories and see that the "buttons" function normally
* click on the item buttons and see that the item is added to the ticket
* click on the item buttons multiple times and see that the quantity and price updates
* click on "Place Order" to place an order
* go to `http://localhost:3000/api/orders` and see that the order has been added

### CODE REVIEW

**Review by mhxynh — APPROVED** [review]

**Comment by gitnamehere** [comment]
@mhxynh it's not ready lol

**Comment by mhxynh** [comment]
@gitnamehere Yeah I know lol. I just reviewed what you already done because I noticed the order ticket part you made could be used in the Payment Screen to display a review of items in an order as they pay

**Review by nhokzminh698 — APPROVED** [review]
YUh

**Comment by mhxynh** [comment]
Is setup-demo suppose to be another file? I only have setup.sql.

**Comment by gitnamehere** [comment]
> `npm run setup-demo`
> 
> In your testing instructions, is setup-demo suppose to be another file? I only have setup.sql.

should be, try pulling the changes again

**Comment by mhxynh** [comment]
> > `npm run setup-demo`
> > In your testing instructions, is setup-demo suppose to be another file? I only have setup.sql.
> 
> should be, try pulling the changes again

Hmm still not getting anything. Is it a file you meant to commit to this PR?

**Comment by gitnamehere** [comment]
so basically what `setup-demo` does is that it runs `setup.sql` and `demo-data.sql` right after

**Comment by nhokzminh698** [comment]
i got the table sql set up thing to work and the example but cant run the npm run start thing

**Comment by gitnamehere** [comment]
> i got the table sql set up thing to work and the example but cant run the npm run start thing

try running it from the root project directory or cd into app and running `node server.js`

**Review by mhxynh — COMMENTED** [review]
Got testing to work, I was just stupid and forgot that this is not on your personal dev branch. Can we change the buttons so that when a user is hovering over it, there is some indication that they can click/are clicking on it?

**Review by mhxynh — APPROVED** [review]
Yippie! Looks goodie to me!

**Comment by nhokzminh698** [comment]
Got it to work (was the env.json thingy)! It looks good

**Pull request merged**
