### PR TITLE
Orders refinement

### PR DESCRIPTION
**Pull request by gitnamehere**
This PR updates how items, orders, and order items are stored in the DB.

- Change item deletion to be a `is_deleted` boolean value, so that if an item is deleted, it will be soft deleted
- Implemented the use of `order_item` in the backend, will be used in sales reporting and other whatnot
  - also added an endpoint to return the order items based on the order id
- Orders now uses the `date_ordered` column
- Added validation without testing the validation (i hope it works lol)

Testing:
- `npm run setup-demo`
- `npm start`
- create some orders at http://localhost:3000/pos/ordering/ and place them
- verify ordering works as normal
- go to http://localhost:3000/api/orders/1
- verify the date_ordered field is the current date
- go to http://localhost:3000/api/orders/items/1
- verify the order items are there
- verify any other code that uses orders works normally

### CODE REVIEW

**Comment by nhokzminh698** [comment]
After the order being placed, I go to `http://localhost:3000/api/orders/1` but it says date_ordered is nulled
image

**Comment by gitnamehere** [comment]
> After the order being placed, I go to `http://localhost:3000/api/orders/1` but it says date_ordered is nulled

it's working for me, have you tried running `setup-demo`?

**Comment by nhokzminh698** [comment]
Ye followed instruction step by step!! let me retry

**Comment by nhokzminh698** [comment]
Weird but it worked now!
image

**Comment by nhokzminh698** [comment]
It doesn't have date in the /pos/orders/ but I assume it going to appear once the payment is done?

**Comment by gitnamehere** [comment]
I was thinking that pos/orders should be changed so that each order would be like a button that takes you to the payment screen in [here](https://cs375-pos-group-project.atlassian.net/jira/core/projects/ATS/board?selectedIssue=ATS-53)

**Comment by nhokzminh698** [comment]
ohh okay!!

**Review by nhokzminh698 — APPROVED** [review]
Looks good!!!

**Comment by wetefok** [comment]
image

**Review by wetefok — APPROVED** [review]
image

**Pull request merged**
