### PR TITLE
POS - Implement voiding of orders

### PR DESCRIPTION
**Pull request by mhxynh**
**Ticket:** **[ATS-51: POS - Finish implementing the ordering process](https://cs375-pos-group-project.atlassian.net/browse/ATS-51?atlOrigin=eyJpIjoiYjgzYmJhMDljODFiNGZjOWI2MThiODc0ZDY2YmYyNjgiLCJwIjoiaiJ9)](https://cs375-pos-group-project.atlassian.net/browse/ATS-52?atlOrigin=eyJpIjoiYjA2YzRjNmJlNzFmNDcwOGFhY2IyZGY1YzIxMDNkYzMiLCJwIjoiaiJ9)**

- Added API endpoints for voiding and refunding
- Added buttons to payment screen for both voiding and refunding

Testing:
- `npm run setup-demo:dev` (If you have not updated your DB recently)
- `npm run start:dev`
- Place order(s) at `http://localhost:3000/pos/ordering/`
- Pay for order at `http://localhost:3000/pos/payment/?id=1`
- Verify orders which have been paid can be refunded
- Verify orders that have not been paid cannot be refunded (nothing should change)
- Verify orders which have been paid cannot be voided (nothing should change)
- Verify orders which have not been paid can be voided
- Verify the above is reflected in the Orders page (play around with the filters)
- Verify upon refunding an order, it is updated in the DB at `http://localhost:3000/api/orders` and user is redirected to `http://localhost:3000/pos/orders/`
- Verify upon voiding an order, it is updated in the DB at `http://localhost:3000/api/orders` and user is redirected to `http://localhost:3000/pos/orders/`

### CODE REVIEW

**Review by nhokzminh698 — APPROVED** [review]
Wild QoL for them cashiers!!! U tell em!!

**Comment by wetefok** [comment]
Verify orders which have been paid cannot be refunded (nothing should change)

This line from testing is making me confucian. Did you mean cannot be voided?
image

**Comment by wetefok** [comment]
Also is it intentional that the buttons require a double-click to void and refund orders?

**Comment by mhxynh** [comment]
> Verify orders which have been paid cannot be refunded (nothing should change)
> 
> This line from testing is making me confucian. Did you mean cannot be voided? image

Sorry, should've double checked, but yes. It means it cannot be voided. Going to update it now.

**Comment by mhxynh** [comment]
> Also is it intentional that the buttons require a double-click to void and refund orders?

Erm, no but I will put a fix in for this rn.

**Review by wetefok — APPROVED** [review]
This truly is some of the code I have ever read in my life.

**Pull request merged**
